package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"
	"fmt"
	"time"

	"github.com/iammrsea/social-app/cmd/server/graphql/graph/model"
	"github.com/iammrsea/social-app/internal/shared/pagination"
	"github.com/iammrsea/social-app/internal/user/app/query"
	"github.com/iammrsea/social-app/internal/user/domain"
)

// ChangeUsername is the resolver for the changeUsername field.
func (r *mutationResolver) ChangeUsername(ctx context.Context, input model.ChangeUsername) (*domain.UserReadModel, error) {
	panic(fmt.Errorf("not implemented: ChangeUsername - changeUsername"))
}

// MakeModerator is the resolver for the makeModerator field.
func (r *mutationResolver) MakeModerator(ctx context.Context, id string) (*domain.UserReadModel, error) {
	panic(fmt.Errorf("not implemented: MakeModerator - makeModerator"))
}

// RegisterUser is the resolver for the registerUser field.
func (r *mutationResolver) RegisterUser(ctx context.Context, input model.RegisterUser) (*domain.UserReadModel, error) {
	panic(fmt.Errorf("not implemented: RegisterUser - registerUser"))
}

// GetUserByID is the resolver for the getUserById field.
func (r *queryResolver) GetUserByID(ctx context.Context, id string) (*domain.UserReadModel, error) {
	panic(fmt.Errorf("not implemented: GetUserByID - getUserById"))
}

// GetUsers is the resolver for the getUsers field.
func (r *queryResolver) GetUsers(ctx context.Context, first *int32, after *string) (*model.UserConnection, error) {
	var limit int32 = 10
	if first != nil {
		limit = *first
	}
	var afterCursor string

	if after != nil {
		decoded, err := pagination.DecodeCursor(*after)
		if err == nil {
			afterCursor = decoded
		}
	}

	result, err := r.Services.UserService.GetUsersHandler.Handle(ctx, query.GetUsersCommand{After: afterCursor, First: limit})

	if err != nil {
		return nil, err
	}

	if len(result.Data) == 0 {
		return &model.UserConnection{
			Edges:    []*model.UserEdge{},
			PageInfo: &pagination.PageInfo{},
		}, nil
	}

	edges := make([]*model.UserEdge, len(result.Data))

	for i, user := range result.Data {
		cursor := user.CreatedAt.UTC().Format(time.RFC3339Nano)
		edges[i] = &model.UserEdge{
			Cursor: pagination.EncodeCursor(cursor),
			Node:   user,
		}
	}

	startCursor := edges[0].Cursor
	endCursor := edges[len(edges)-1].Cursor

	return &model.UserConnection{
		Edges: edges,
		PageInfo: &pagination.PageInfo{
			HasNextPage:     result.PaginationInfo.HasNext,
			HasPreviousPage: afterCursor != "",
			StartCursor:     startCursor,
			EndCursor:       endCursor,
		},
	}, nil
}

// Role is the resolver for the role field.
func (r *userResolver) Role(ctx context.Context, obj *domain.UserReadModel) (domain.UserRole, error) {
	panic(fmt.Errorf("not implemented: Role - role"))
}

// ReputationScore is the resolver for the reputationScore field.
func (r *userReputationResolver) ReputationScore(ctx context.Context, obj *domain.UserReputation) (int32, error) {
	panic(fmt.Errorf("not implemented: ReputationScore - reputationScore"))
}

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

// UserReputation returns UserReputationResolver implementation.
func (r *Resolver) UserReputation() UserReputationResolver { return &userReputationResolver{r} }

type userResolver struct{ *Resolver }
type userReputationResolver struct{ *Resolver }
