version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: social-app-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=social-app
    volumes:
      - mongodb_data:/data/db
    networks:
      - social-app-network
    restart: unless-stopped
    # Running without authentication for simplicity in development
    command: ["--noauth"]

  mongo-express:
    image: mongo-express:latest
    container_name: social-app-mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - social-app-network
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  social-app-network:
    driver: bridge
