// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ChangeUsername struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterUser struct {
	Email    string `json:"email"`
	Username string `json:"username"`
}

type VoteInput struct {
	UserID string `json:"userId"`
	PostID string `json:"postId"`
	Type   string `json:"type"`
}
