// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/iammrsea/social-app/internal/shared/pagination"
	"github.com/iammrsea/social-app/internal/user/domain"
)

type AwardBadge struct {
	ID    string `json:"id"`
	Badge string `json:"badge"`
}

type ChangeUsername struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterUser struct {
	Email    string `json:"email"`
	Username string `json:"username"`
}

type UserConnection struct {
	Edges    []*UserEdge          `json:"edges"`
	PageInfo *pagination.PageInfo `json:"pageInfo"`
}

type UserEdge struct {
	Node   *domain.UserReadModel `json:"node"`
	Cursor string                `json:"cursor"`
}

type VoteInput struct {
	UserID string `json:"userId"`
	PostID string `json:"postId"`
	Type   string `json:"type"`
}
